'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Provider} from "react-redux";
import {setupStore} from "@/store/store";
import styles from "@/app/globals.scss";
import {PERSIST} from "redux-persist/es/constants";
import {persistStore} from "redux-persist";
import {store} from "next/dist/build/output/store";
import {PersistGate} from "redux-persist/integration/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

let persistor = persistStore(setupStore());

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <Provider store={setupStore()}>

          <html lang="en">
              <body className={`${geistSans.variable} ${geistMono.variable}`}>
                  <PersistGate persistor={persistor}>
                    {children}
                  </PersistGate>
              </body>
          </html>
      </Provider>
  );
}
